### ISSUE TITLE
How to test components that uses ngx-propserve

### ISSUE THREAD

**Issue by mgalante** [aleics/ngx-propserve#3]
i have this input: 

```typescript
@ObservableInput<boolean>('autocomplete') public autocomplete$: Observable<boolean>;
```

and i would like to set a value to it in my test.

```typescript
   component.autocomplete = true;
```
How can i do it?

**Comment by aleics** [comment]
Hi @mgalante,

Thank you for checking out this small library! :smile: 

Since `autocomplete` is created on the fly by the `@ObservableInput` decorator, there's no types definition associated to this property. If you can live with that, you can check out [the unit tests](https://github.com/aleics/ngx-propserve/blob/master/test/observable-input.test.ts) for this decorator. There I use `any` type inference, or you can access dynamic properties by doing:

```ts
component['autocomplete'] = true;
```

Doesn't this work for you?

**Comment by mgalante** [comment]
Great :)  I will let you know if i make any improvement!
