### ISSUE TITLE
Visual Studio Code 1.49.2 reports an error

### ISSUE THREAD

**Issue by mgalante** [aleics/ngx-propserve#7]
Hi Aleics!
How are you? its me again bodering you. 
My team and I update VSCode to the lastest version and we are getting the following error:

```
Property 'conteiner$' is used before its initialization.ts(2729)
cards-layout.component.ts(35, 43): 'conteiner$' is declared here.

Property 'minWidth$' is used before its initialization.ts(2729)
cards-layout.component.ts(36, 39): 'minWidth$' is declared here.

Property 'gutter$' is used before its initialization.ts(2729)
cards-layout.component.ts(37, 36): 'gutter$' is declared here.
```

Our code is like this;

```ts 

export class CardsLayoutComponent implements OnInit, OnDestroy {

/* ... */

 @ViewChild('container') @AsObservable() conteiner$: Observable<ElementRef>;
  @Input('min-width') @AsObservable() minWidth$: Observable<number>;
  @Input('gutter') @AsObservable() gutter$: Observable<number>;

/* ... */

 cardWidth$: Observable<number[]> = combineLatest(
//THIS LINES HAVE ERRORS:
    this.responsiveService.scrollResize$,
    this.conteiner$,
    this.minWidth$.pipe(map(width => width === undefined ? CARD_MIN_WIDHT : width)),
    this.gutter$.pipe(map(gap => gap ? gap : CARDS_GAP))
  ).pipe(

/* ... */
)
```

Thanks a lot and have nice weekend my friend

Migue

**Comment by aleics** [comment]
Hi Migue!

Thank you for opening the issue. No bothering at all :)

Are you sure is this related to the Visual Studio Code version? It sounds more to me that this is a Typescript error. Maybe the version used in the IDE has switched when updating? In the bottom bar on the right, you should be able to see the Typescript version that you are using.

When using strict property initialization, Typescript informs you about using a variable that has not been initialised. Since `@AsObservable` initializes the properties internally, Typescript is not aware about it. Could you try to use [definite assignment assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization), by marking the properties with the `!` operator?

```ts
@Input('min-width') @AsObservable() minWidth$!: Observable<number>;
@Input('gutter') @AsObservable() gutter$!: Observable<number>;
```

I've used the same for the tests [here](https://github.com/aleics/ngx-propserve/blob/2b7b2958b212fc7e8f0c185032835ef605cf661e/test/as-observable.test.ts#L6).

Wish you a nice weekend as well! :)

**Comment by mgalante** [comment]
Thanks for your response!  My team and i love your plugin, it`s a very valuable utility for us.
